export const gh = {
  fileClass: 'file',
  fileWrapperClass: 'js-diff-progressive-container',
  explorerContainerClass: 'diff-view',
  pageContainerClass: 'new-discussion-timeline',
  filesChangedId: 'files_tab_counter',
}

/* Extension specific classes */
export const styleClass = {
  root: 'gde',
  icon: 'gde__icon',
  loader: 'gde__loader',
  fileIcon: 'gde__file-icon',
  caretIcon: 'gde__caret-icon',
  pageContainer: 'gde__page',
  activeFile: 'gde__file--active',
  activeExplorer: 'gde__item--active',
  viewedExplorer: 'gde__item--viewed',
  explorerContainer: 'gde__container',
  minimizedContainer: 'gde__container--minimized',
  explorerHeader: 'gde__header',
  minimizedHeaderContainer: 'gde__header--minimized',
  explorerHeaderTitle: 'gde__header-title',
  minimizedHeaderTitle: 'gde__header-title--minimized',
  explorerHeaderLogo: 'gde__header-logo',
  explorerHeaderTitleContainer: 'gde__header-title-container',
  explorerFolderHeader: 'gde__folder-header',
  explorerHeaderMenu: 'gde__folder-header-menu',
  explorerMenuButton: 'gde__menu-btn',
  explorerActiveMenuButton: 'gde_menu-btn--active',
  explorerItem: 'gde__item',
  fileDiffContainer: 'gde__files',
  fileDiff: 'gde__file',  
  explorerFolderContainer: 'gde__nested-files',
  explorerFolderTopContainer: 'gde__nested-files-container',
  closedFolder: 'gde__folder-closed',
}